name: Check code style using clj-kondo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: DeLaGuardo/clojure-lint-action@master
      with:
        clj-kondo-args: --lint src --config ./dev/lint/clj-kondo.edn
        github_token: ${{ secrets.GITHUB_TOKEN }}
